# Existing
org.gradle.jvmargs=-Xmx1536m
android.useAndroidX=true
android.nonTransitiveRClass=true
android.kotlin.stdlib.default.dependency=false

# Build performance only
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Smaller generated code
android.enableAppCompileTimeRClass=false

# Disable generated BuildConfig if unused
android.defaults.buildfeatures.buildconfig=false

# Only if you don't use RenderScript
android.defaults.buildfeatures.renderscript=false

# Only if you don't use AIDL
android.defaults.buildfeatures.aidl=false

# Only if you don't use shaders
android.defaults.buildfeatures.shaders=false

# R8 optimizations
android.r8.optimizedResourceShrinking=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# Allow KSP to add source sets
android.disallowKotlinSourceSets=false
